const finances = [
  {
    type: "Salary",
    description: "Salário Outubro",
    date: new Date("10/01/2022"),
    value: 3791.66,
    payment: "Cash",
  },
  {
    type: "Food",
    description: "Ifood Açaí",
    date: new Date("10/01/2022"),
    value: -22.94,
    payment: "Cash",
  },
  {
    type: "Others",
    description: "Marinete",
    date: new Date("10/01/2022"),
    value: 261.61,
    payment: "Cash",
  },
  {
    type: "Food",
    description: "Ifood Açaí",
    date: new Date("10/01/2022"),
    value: -22.94,
    payment: "Cash",
  },
  {
    type: "Shop",
    description: "Riachuelo",
    date: new Date("10/01/2022"),
    value: -22.94,
    payment: "Cash",
  },
  {
    type: "Others",
    description: "Marinete",
    date: new Date("10/01/2022"),
    value: 258.24,
    payment: "Cash",
  },
  {
    type: "Supermarket",
    description: "Telefrango",
    date: new Date("10/04/2022"),
    value: -258.24,
    payment: "Cash",
  },
  {
    type: "Maintenance",
    description: "Carro",
    date: new Date("10/08/2022"),
    value: -258.24,
    payment: "Cash",
  },
  {
    type: "House",
    description: "Faxina",
    date: new Date("10/01/2022"),
    value: -150,
    payment: "Cash",
  },
  {
    type: "Insurance",
    description: "Plano Marinete",
    date: new Date("10/01/2022"),
    value: -150,
    payment: "Cash",
  },
  {
    type: "Benefit",
    description: "Caju",
    date: new Date("10/01/2022"),
    value: 500,
    payment: "Cash",
  },
];

export default finances;
